### ISSUE TITLE
Canceling the chat event makes other plugins (like DiscordSRV) not behave correctly

### ISSUE THREAD

**Issue by NyaomiDEV** [Andre601/HexChat#1]
In short, DiscordSRV listens to the chat event to get messages and mirror them over to Discord for a seamless chat experience.

Since this plugin cancels that event to send its custom format, DiscordSRV sees that the event is canceled and it does nothing.

Tested on Paper 1.16.2 with HexChat 1.5.0

**Comment by Andre601** [comment]
This is normal. You can make DiscordSRV send a message no mattr if it wss canceled or not.

I will look if I can do something, but the API of DiscordSRV is kinda trash, so there won't be a guarantee.

**Comment by NyaomiDEV** [comment]
> This is normal. You can make DiscordSRV send a message no mattr if it wss canceled or not.

I don't see any configuration entry regarding this, in DiscordSRV

By the way, why aren't you just setting the format via `event.setFormat()`? Any particular reason why?

**Comment by Andre601** [comment]
> > This is normal. You can make DiscordSRV send a message no mattr if it wss canceled or not.
> 
> I don't see any configuration entry regarding this, in DiscordSRV

There is a setting. Just look closely or ask on their Discord.

> By the way, why aren't you just setting the format via `event.setFormat()`? Any particular reason why?

Because that's not how it works?
HexChat doesn't just apply colors and calls it a day. It also allows applying hover text and click actions.

**Comment by NyaomiDEV** [comment]
> Because that's not how it works?
> HexChat doesn't just apply colors and calls it a day. It also allows applying hover text and click actions.

I got it now! Thanks for the clarification...
wait, won't setting up an empty string as a format in the event just sort of work around the issue?

**Comment by Vankka** [comment]
> This is normal. You can make DiscordSRV send a message no mattr if it wss canceled or not.  

That's a debugging option which should never be altered other than for debugging purposes, that is the least valid solution to this problem. Clear the recipient list.

**Comment by Andre601** [comment]
> > This is normal. You can make DiscordSRV send a message no mattr if it wss canceled or not.
> 
> That's a debugging option which should never be altered other than for debugging purposes, that is the least valid solution to this problem. Clear the recipient list.

This would be an unreliable and honestly stupid way to do.
Quote from the [Javadoc](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/AsyncPlayerChatEvent.html#getRecipients())
> Gets a set of recipients that this chat message will be displayed to.
> **The set returned is not guaranteed to be mutable** and may auto-populate on access. Any listener accessing the returned set should be aware that it may reduce performance for a lazy set implementation.
> 
> Listeners should be aware that modifying the list may throw UnsupportedOperationException if the event caller provides an unmodifiable set.

And according to the docs is there also not a `setRecipients` method to utilize here which makes this just more stupid.

`setFormat` would also not be an option as it is a NotNull-annotated one and the same goes for `setMessage` so from my checks is there not any other way - other than cancelling and then manually sending the message - to do this how I want it to work.

Like I said will I look into hoking this thing into DiscordSRV and make it send a message to the default channel DiscordSRV has.

**Comment by Vankka** [comment]
> The set returned is not guaranteed to be mutable

Haven't yet encountered a single time it would not be mutable

What you're doing is beyond
> honestly stupid

you're breaking every plugin that has any reliance on chat messages here, not just DiscordSRV.

**Comment by Andre601** [comment]
I still don't see a clear way, where just clearing the set of recipients would actually do something, as I don't beliebe Spigot to work like that and that you still need to set/alter the recipients somehow.

But if it makes you really happy will I set a try-catch that tries clearing the set and if it fails will it just cancel the event and send a Message through DiscordSRV's API.

**Comment by Vankka** [comment]
doing `event.getRecipients().clear();` works fine (in that nobody receives the message, without it being cancelled), and is used in other plugins such as FactionsUUID [source](https://github.com/drtshock/Factions/blob/62ad62217034bd82b4b37635fc44cbb245ddb758/src/main/java/com/massivecraft/factions/listeners/FactionsChatListener.java#L181) and many many more according to a quick [github search](https://github.com/search?q=event.getRecipients%28%29.clear%28%29%3B&type=Code), if it didn't work I doubt a plugin the size of FactionsUUID would *still* be using it

**Comment by Andre601** [comment]
I will do it like that then, but if there will even be one single person that reports an issue will you be the first one I will forward that guy towards for complaining.

In other news does the system work now as expected and I'll release a new version soon.
